{ config, ... }:
let
  apps = "${config.home.homeDirectory}/.dotfiles/apps";
  link = path: config.lib.file.mkOutOfStoreSymlink "${apps}/${path}";
in
{
  home.file = {
    # ~/.zshrc is generated by apps/zsh/zsh.nix, not symlinked.
    ".p10k.zsh".source = link "p10k/.p10k.zsh";
    ".claude/settings.json".source = link "claude/settings.json";
  };

  xdg.configFile = {
    "ghostty/config".source = link "ghostty/config";
  };
}
