[env]
TERM = "xterm-256color"

# Only open URLs on Cmd + click
[[hints.enabled]]
command = "open"
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.8
blur = true

option_as_alt = "Both"

[font]
normal.family = "B612 Mono"

size = 15

[general]
import = [
  "~/.config/alacritty/catppuccin-macchiato.toml"
]
